---
- hosts: centosgroup
  become: true
  vars:
      
    paquetes:
      - httpd
      - php-fpm

  tasks:
  - name: Instalacion de apache
    yum:
      name: '{{ paquetes }}'
      state: present
  - name: Levantar Servicio
    service:
      name: httpd 
      state: started
  - name: Abrir puertos http y https
    firewalld:
      service: "{{ item }}"    
      permanent: true
      state: enabled
    loop:
      - http
      - https  
  - name: Reinciar el firewall
    service: 
      name: firewalld 
      state: restarted    

...
